### ISSUE TITLE
Path fonts and indicatior image loading incorrect

### ISSUE THREAD

**Issue by n2lose** [gitvani/ionic-2-slick-carousel#1]
Hi,

I got this issue: 
![ionic2-slick](https://cloud.githubusercontent.com/assets/443793/26816224/c77e1df4-4aba-11e7-9409-ff095c6ffffe.png)
Could you take a look at this? 
I have tried to update to correct path for fonts and imae axjax-loader.gif on node_modules, but it doesn't work. 
How can i specific good path for that? 
Anyway, slick slider still works fine.

Thanks,
Lam

**Comment by VibeAICoder** [comment]
Hi n2lose, 
Your project is missing font and gif files. You should go to library and copy these files into project.

**Comment by n2lose** [comment]
Hi gitvani,

I know it missing fonts and gif files, but i as check in the node_modules, they was there and the path link to fonts, gif files seems correct. 
Why we can import these from there? And i don't know why the error has path: /build/fonts and /build/ajax-loader.gif

So, i can put it in the folder assets/fonts  and images,...but how can i import these?

**Comment by n2lose** [comment]
I have just fixed it by the way check the instances before init. 
E.g: 
`
$('.myCarousel').not('.slick-initialized').slick({
      dots: true,
      centerMode: true,
      infinite: true,
      centerPadding: '30px',
      arrows: false,
      slidesToShow: 1
 });
`

But i got another issue: after swipe to first slide, seems it refresh current slick and set Width of items again with big value  +10000px.
May it related issue https://github.com/kenwheeler/slick/issues/2167
Do you have any suggestion for me?

**Comment by n2lose** [comment]
I fixed it. So, i closed this issue.
